version: "3.8"

services:

  backend:
    build: .
    container_name: backend
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core.celery worker 
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis

  redis:
      image: "redis:alpine"