# Generated by Django 4.2.2 on 2023-06-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        already_admin = False
        if User.objects.filter(username="admin", is_superuser=True).count() == 1:
            already_admin = True

        if not already_admin:
            superuser = User.objects.create_superuser(
                username="admin",
                email="admin@admin.com",
                password="Admin123")

            superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
